# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LenderCurrentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_repaid', models.FloatField(default=0)),
                ('interest_repaid', models.FloatField(default=0)),
                ('principal_left', models.FloatField(default=0)),
                ('interest_left', models.FloatField(default=0)),
                ('tenure_left', models.FloatField(default=0)),
                ('emr', models.FloatField(default=0)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='LenderDeviabTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('payment', models.FloatField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('payment_mode', models.IntegerField()),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('udf_1', models.CharField(max_length=30)),
                ('udf_2', models.CharField(max_length=30)),
                ('udf_3', models.CharField(max_length=30)),
                ('udf_4', models.CharField(max_length=30)),
                ('udf_5', models.CharField(max_length=30)),
                ('product_info', models.CharField(max_length=30)),
                ('additional_charges', models.FloatField(default=0)),
                ('split_info', models.CharField(max_length=30)),
                ('error_message', models.CharField(max_length=30)),
                ('notification', models.CharField(max_length=30)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='LenderWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='LenderWithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('requested_at', models.DateTimeField()),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(0, b'Processing'), (1, b'Completed'), (2, b'Pending')], default=0)),
                ('lender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitalAmount', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lenderdeviabtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Project'),
        ),
    ]
