# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 02:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendercurrentstatus',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lendercurrentstatus',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender'),
        ),
        migrations.AlterField(
            model_name='lendercurrentstatus',
            name='tenure_left',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 2, 1, 47, 408479)),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 2, 1, 47, 406911)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 2, 1, 47, 409687)),
        ),
    ]
