# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lenderdeviabtransaction',
            old_name='payment',
            new_name='payment_id',
        ),
    ]
