# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0002_auto_20160417_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=13, null=True)),
                ('avatar', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='capitalAmount',
            new_name='raisedAmount',
        ),
        migrations.AddField(
            model_name='lender',
            name='avatar',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 3, 10, 42, 881656)),
        ),
        migrations.AddField(
            model_name='project',
            name='offlistDate',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='place',
            field=models.CharField(default='Dhamdha', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='targetAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Pilot 2', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 3, 10, 42, 882366)),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 3, 10, 42, 880551)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 3, 10, 42, 883570)),
        ),
        migrations.AddField(
            model_name='borrower',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Project'),
        ),
    ]
