# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0003_auto_20160216_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
