# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0003_auto_20160417_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='lytyfy_rest.Project'),
        ),
        migrations.AlterField(
            model_name='lendercurrentstatus',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lytyfy_rest.Lender'),
        ),
        migrations.AlterField(
            model_name='lendercurrentstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenders', to='lytyfy_rest.Project'),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 12, 51, 30, 231233)),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 12, 51, 30, 229207)),
        ),
        migrations.AlterField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 12, 51, 30, 230376)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 12, 51, 30, 232474)),
        ),
    ]
