# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0004_auto_20160502_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='avatar',
            field=s3direct.fields.S3DirectField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_transactions', to='lytyfy_rest.Lender'),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='lytyfy_rest.Project'),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 11, 35, 39, 547029)),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 11, 35, 39, 545334)),
        ),
        migrations.AlterField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 11, 35, 39, 546262)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 11, 35, 39, 548267)),
        ),
    ]
