# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0004_auto_20160216_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Lender'),
        ),
    ]
