# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0005_auto_20160529_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderdeviabtransaction',
            name='transactions_type',
            field=models.CharField(default='debit', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrower',
            name='avatar',
            field=s3direct.fields.S3DirectField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='lendercurrentstatus',
            name='tenure_left',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='customer_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='customer_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='customer_phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='payment_mode',
            field=models.IntegerField(choices=[(0, b'CC'), (1, b'DC'), (2, b'NB')], null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 21, 17, 25, 458029)),
        ),
        migrations.AlterField(
            model_name='lenderwallet',
            name='lender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='lytyfy_rest.Lender'),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 21, 17, 25, 454840)),
        ),
        migrations.AlterField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 21, 17, 25, 456733)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 21, 17, 25, 460200)),
        ),
    ]
