# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 04:24
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0006_auto_20160701_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invite',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='dob',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female'), (2, b'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
