# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0007_auto_20160815_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='social_token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='uid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='lenderwithdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='enlistDate',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
