# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0007_auto_20160815_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderdeviabtransaction',
            name='wallet_money',
            field=models.FloatField(default=0.0),
        )
    ]
