# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0008_auto_20161008_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('avatar', s3direct.fields.S3DirectField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', s3direct.fields.S3DirectField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=s3direct.fields.S3DirectField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lenderdeviabtransaction',
            name='payment_mode',
            field=models.IntegerField(choices=[(0, b'CC'), (1, b'DC'), (2, b'NB'), (3, b'WL')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='social_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='field_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.FieldPartner'),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lytyfy_rest.Product'),
        ),
    ]
