# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0008_auto_20160821_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='social_token',
            field=models.TextField(null=True),
        ),
    ]
