# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0009_auto_20161008_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
