# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0010_auto_20161009_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', s3direct.fields.S3DirectField(blank=True, max_length=64, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='lytyfy_rest.Project')),
            ],
        ),
    ]
