# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 19:18
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lytyfy_rest', '0011_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_img',
            field=s3direct.fields.S3DirectField(blank=True, max_length=64, null=True),
        ),
    ]
